### ISSUE TITLE
Ubuntu 14.04?

### ISSUE THREAD

**Issue by IonicaBizau** [kekekeks/monodevelop-appmenu#2]
``` sh
W: Failed to fetch http://ppa.launchpad.net/keks9n/monodevelop-latest/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/keks9n/monodevelop-latest/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by kekekeks** [comment]
I'm afraid it's no longer compatible with recent Ubuntu and MonoDevelop versions anyway.

**Comment by IonicaBizau** [comment]
Are there any workarounds for bringing the global Unity menu in MonoDevelop?

**Comment by IonicaBizau** [comment]
![screenshot from 2014-10-07 21 04 15](https://cloud.githubusercontent.com/assets/2864371/4547367/5fdcc7c6-4e4c-11e4-923a-baa573598232.png)

This is how it looks now.

**Comment by kekekeks** [comment]
MonoDevelop adds menu items at the moment when user actually opens menu. Unity doesn't even add menu items that don't have any subitems. That extension tried to emulate that "user opens menu event"

**Comment by kekekeks** [comment]
That behaviour is caused by `export UBUNTU_MENUPROXY=0` in /usr/bin/monodevelop. If you remove it, you either get empty menus (Ubuntu>13.04) or no menus at all (Ubuntu<13.04)

**Comment by IonicaBizau** [comment]
>  If you remove it, you either get empty menus (Ubuntu>13.04)

Interesting stuff here. The global menu appears, but like you said, each one is empty. Is this a known bug? Are there any ways to solve this?
